// Stamp the build with the package version:
//  - src/lib/version.js  → APP_VERSION constant bundled into the app (pre-build)
//  - dist/version.json   → the fetchable manifest the update check reads (post-build)
// Wired as: node scripts/make-version.mjs && vite build && node scripts/write-manifest.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = pkg.version;
// Build timestamp (for the About page: version · build date · channel).
const builtAt = new Date().toISOString();

writeFileSync(
  join(root, "src/lib/version.js"),
  `// Generated by scripts/make-version.mjs at build time — do not edit by hand.\n` +
    `// dist/version.json (from write-manifest.mjs) is what the update check,\n` +
    `// and later the native APK/EXE updaters, poll for newer versions.\n` +
    `export const APP_VERSION = "${version}";\n` +
    `export const APP_BUILT_AT = "${builtAt}";\n` +
    `export const APP_CHANNEL = "stable";\n`
);
console.log(`version stamped: v${version}`);
