// Generated by scripts/make-version.mjs at build time — do not edit by hand.
// dist/version.json (from write-manifest.mjs) is what the update check,
// and later the native APK/EXE updaters, poll for newer versions.
export const APP_VERSION = "0.3.6";
export const APP_BUILT_AT = "2026-09-27T19:08:24.391Z";
export const APP_CHANNEL = "stable";
